pipeline {
    agent any

    tools {
        jdk 'JDK21'
        maven 'Maven3'
    }

    stages {

        stage('Build') {
            steps {
                dir('Java-CI-demo') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Java-CI-demo') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Java-CI-demo') {
                    bat 'mvn package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('Java-CI-demo') {
                    withSonarQubeEnv('SonarQube') {
                        bat 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar'
                    }
                }
            }
        }
    }
}
